### ISSUE TITLE
Regarding the FGSM attack generation

### ISSUE THREAD

**Issue by ripankundu** [afraarslan/adversarial-attacks#1]
ValueError: Attempt to convert a value (None) with an unsupported type (<class 'NoneType'>) to a Tensor. 
when I did  tf.sign(gradientFunction) the error come. Could you please fix that if it is possible

X_tf = tf.convert_to_tensor(X_test, dtype=tf.float32)
with tf.GradientTape() as tape:
    tape.watch(X_tf)
    lossFunction = mean_squared_error(X_tf, predictions)
gradientFunction = tape.gradient(lossFunction, X_tf)
signed_grad = tf.sign(gradientFunction)
perturbed_data = X_test + 0.2 * signed_grad
X_perturbed = perturbed_data.numpy()

  File "C:\Users\USER\AppData\Roaming\Python\Python37\site-packages\tensorflow_core\python\ops\gen_math_ops.py", line 9695, in sign
    name, _ctx._post_execution_callbacks, x)

_FallbackException: This function does not handle the case of the path where all inputs are not already EagerTensors.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "<ipython-input-3-6b7a10969ba7>", line 14, in <module>
    signed_grad = tf.sign(gradientFunction)

  File "C:\Users\USER\AppData\Roaming\Python\Python37\site-packages\tensorflow_core\python\ops\gen_math_ops.py", line 9700, in sign
    x, name=name, ctx=_ctx)

  File "C:\Users\USER\AppData\Roaming\Python\Python37\site-packages\tensorflow_core\python\ops\gen_math_ops.py", line 9745, in sign_eager_fallback
    _attr_T, (x,) = _execute.args_to_matching_eager([x], _ctx)

  File "C:\Users\USER\AppData\Roaming\Python\Python37\site-packages\tensorflow_core\python\eager\execute.py", line 257, in args_to_matching_eager
    t, dtype, preferred_dtype=default_dtype, ctx=ctx))

  File "C:\Users\USER\AppData\Roaming\Python\Python37\site-packages\tensorflow_core\python\framework\ops.py", line 1296, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)

  File "C:\Users\USER\AppData\Roaming\Python\Python37\site-packages\tensorflow_core\python\framework\constant_op.py", line 286, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)

  File "C:\Users\USER\AppData\Roaming\Python\Python37\site-packages\tensorflow_core\python\framework\constant_op.py", line 227, in constant
    allow_broadcast=True)

  File "C:\Users\USER\AppData\Roaming\Python\Python37\site-packages\tensorflow_core\python\framework\constant_op.py", line 235, in _constant_impl
    t = convert_to_eager_tensor(value, ctx, dtype)

  File "C:\Users\USER\AppData\Roaming\Python\Python37\site-packages\tensorflow_core\python\framework\constant_op.py", line 96, in convert_to_eager_tensor
    return ops.EagerTensor(value, ctx.device_name, dtype)

ValueError: Attempt to convert a value (None) with an unsupported type (<class 'NoneType'>) to a Tensor.

**Comment by RedentorLXL** [comment]
The loss Function may be wrong,it should be determined by Y_True and Y_prediction 
The Correct form may be：lossFunction = mean_squared_error(Y_tf, lstm_predictions)

**Comment by RedentorLXL** [comment]
The lossfunction may be wrong, it should be determined by Y_ True and Y_ Prediction.
Correct form may be:
lossFunction = mean_squared_error(Y_tf, predictions)
